version: "2"

services:

  nodered:
    extends:
      file: nodered.yml
      service: nodered
    links:
      - influxdb:influxdb

  influxdb:
    extends:
      file: influxdb.yml
      service: influxdb

  grafana:
    extends:
      file: grafana.yml
      service: grafana
    links:
      - influxdb:influxdb

volumes:
  grafana-storage:
    external: true
