version: "2"

services:

  grafana:
    image: grafana/grafana-oss
    environment:
      GF_SECURITY_ADMIN_PASSWORD: #MY_GF_SECURITY_ADMIN_PASSWORD#
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel,mtanda-heatmap-epoch-panel,briangann-gauge-panel,jdbranham-diagram-panel,snuids-radar-panel,fatcloud-windrose-panel, agenty-flowcharting-panel
    volumes:
       - grafana-storage:/var/lib/grafana
    ports:
      - 80:3000
    restart: unless-stopped
