version: "2"

services:

  influxdb:
    image: influxdb:1.8
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: #ADMIN_PASS#
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: #USER_PASS#
    volumes:
            - /data/influxdb/:/var/lib/influxdb:rw
            - /data/influxdb.conf:/etc/influxdb/influxdb.conf
    ports:
      - 8086:8086 #8086 HTTP API port
      - 8083:8083 #8083 Administrator interface port, if it is enabled
    restart: unless-stopped
